steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - '/deployment/deploy-dev.yaml'
options:
  build:
    service_account: 516957045707-compute@developer.gserviceaccount.com
