apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-10-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-10-app
  template:
    metadata:
      labels:
        app: nestjs-10-app
    spec:
      containers:
        - name: nestjs-10-app
          image: gcr.io/ceremonial-team-424503-u1/nestjs-10-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-10-app
  labels:
    tier: backend
spec:
  selector:
    app: nestjs-10-app
    tier: backend
  ports:
    - name: nestjs-10-app
      protocol: TCP
      port: 3000