apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-10-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-10-app
  template:
    metadata:
      labels:
        app: nestjs-10-app
    spec:
      containers:
        - name: nestjs-10-app
          image: gcr.io/ceremonial-team-424503-u1/nestjs-10-app:latest
          ports:
            - containerPort: 3000
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
          volumeMounts:
            - name: instance-credentials-volume
              mountPath: /secrets/
              readOnly: true
          command:
            - "/cloud_sql_proxy"
            - "-instances=ceremonial-team-424503-u1:asia-northeast1:nestjs-10-sql=tcp:3306"
            - "-credential_file=/secrets/credentials.json"
      volumes:
        - name: instance-credentials-volume
          secret:
            secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-10-service
spec:
  selector:
    app: nestjs-10-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer