apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-10-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-10-app
  template:
    metadata:
      labels:
        app: nestjs-10-app
    spec:
      containers:
        - name: nestjs-10-app
          image: gcr.io/ceremonial-team-424503-u1/nestjs-10-app:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: cloudsql-sockets
              mountPath: /cloudsql
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
          command:
            - "/cloud_sql_proxy"
            - "-instances=prd-wanqol-pj:asia-northeast1:prd-wanqol-pj=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets
              readOnly: true
            - name: cloudsql-sockets
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql-sockets
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nestjs-10-service
spec:
  selector:
    app: nestjs-10-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer